version: "3.3"

networks:
  restapi:
    driver: bridge

services:
  php:
    build: .
    ports:
      - 8080:8080
      - 80:80
    networks:
      - restapi
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    networks:
      - restapi
    volumes:
      - $HOME/projects/docker/volumes/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9.4
    ports:
      - 8888:80
    networks:
      - restapi
    environment:
      - PMA_ARBITRARY=1